Inicio workflows

diff --git a/.github/workflows/manual-exec.yaml b/.github/workflows/manual-exec.yaml
--- a/.github/workflows/manual-exec.yaml
+++ b/.github/workflows/manual-exec.yaml
@@ -4,27 +4,30 @@ on:
   workflow_dispatch:
     inputs:
       action:
-        description: "Select Terraform action"
+        description: "plan | apply | destroy"
         required: true
         type: choice
         default: plan
-        options:
-          - plan
-          - apply
-          - destroy
+        options: [plan, apply, destroy]
 
 jobs:
-  terraform:
+  run:
     runs-on: stemdo-labs
-
     env:
-      AWS_REGION: eu-west-3
+      AWS_REGION: ${{ vars.AWS_REGION }}
       TF_IN_AUTOMATION: "true"
 
     steps:
-      - name: Clone private infra repo (PAT classic)
+      - name: Checkout repo public
+        uses: actions/checkout@v4
+
+      - name: Setup SSH for private modules
+        shell: bash
         run: |
-          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/stemdo-labs/terraform-weekly-exercise-fsancha.git infra
+          mkdir -p ~/.ssh
+          echo "${{ secrets.TF_MODULES_SSH_KEY }}" > ~/.ssh/id_ed25519
+          chmod 600 ~/.ssh/id_ed25519
+          ssh-keyscan -t rsa,ed25519 github.com >> ~/.ssh/known_hosts
 
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3
@@ -32,7 +35,7 @@ jobs:
           terraform_wrapper: false
 
       - name: Terraform init
-        working-directory: infra
+        working-directory: modulo-weekly-exercise
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
@@ -40,19 +43,15 @@ jobs:
         run: terraform init -input=false
 
       - name: Terraform ${{ inputs.action }}
-        working-directory: infra
+        working-directory: modulo-weekly-exercise
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
         run: |
-          if [ "${{ inputs.action }}" = "plan" ]; then
-            terraform plan -input=false
-          elif [ "${{ inputs.action }}" = "apply" ]; then
-            terraform apply -input=false -auto-approve
-          elif [ "${{ inputs.action }}" = "destroy" ]; then
-            terraform destroy -input=false -auto-approve
-          else
-            echo "Invalid action"
-            exit 1
-          fi
+          case "${{ inputs.action }}" in
+            plan) terraform plan -input=false ;;
+            apply) terraform apply -input=false -auto-approve ;;
+            destroy) terraform destroy -input=false -auto-approve ;;
+            *) echo "Invalid action" && exit 1 ;;
+          esac
